### ISSUE TITLE
refreshSession not working

### ISSUE THREAD

**Issue by antojsh** [frsechet/cognito-user-pool#12]
``
D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^

TypeError: Cannot read property 'getRefreshToken' of null
    at cognitoUser.refreshSession (D:\Proyects\Adonis\ride_me\node_modules\cognito-user-pool\src\methods\refreshSession.js:28:25)
    at Response.<anonymous> (D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\lib\CognitoUser.js:1140:16)
    at Request.<anonymous> (D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\request.js:364:18)
    at Request.callListeners (D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
    at Request.emit (D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (D:\Proyects\Adonis\ride_me\node_modules\amazon-cognito-identity-js\node_modules\aws-sdk\lib\state_machine.js:14:12)
``

**Comment by frsechet** [comment]
How about hello first, then some context about what you tried already?

**Comment by frsechet** [comment]
Closing for lack of information.
